name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # nyimpen session
  shared_preferences: ^2.2.3
  # buat ambil data API
  http: ^1.2.1
  # LBS lokasi
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  crypto: ^3.0.3
  flutter_local_notifications: ^17.1.2  
  timezone: ^0.9.3                      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
